jasypt:
  encryptor:
    password: tonny
    algorithm: PBEWithMD5AndDES
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ty_horse?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: ENC(uReC8yNNbRfgsr5JJayCLw==)
    password: ENC(p6gL5Du/h7T3DopY+1Ntgw==)
  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  messages:
    basename: i18n.login
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  mail:
    host: 220.181.12.16
    username: z332069@163.com
    password: yintao110
    default-encoding: UTF-8
  http:
    multipart:
      enable: true
      file-size-threshold: 0
      location: D:\
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yrxc.horse.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
tencent:
  appId: 1400288767
  appKey: 208bee36bd60dc5fd6458e26a7eb0538
  templateId: 871112
  templateId2: 1305179
  smsSign: 鱼人新创
mail:
  smtp:
    service: 220.181.12.16
    port: 25
  from:
    address: z332069@163.com
    nickname: 开山怪
    smtp:
      pwd: yintao110
server:
  port: 443
  ssl:
    keystore: E:/yurenxinchuang.com.jks
    keystore-password: 1bacg436xc280
    keystore-type: JKS
    key-alias: jks
  tomcat:
    uri-encoding: UTF-8
user:
  file:
    path: E:/img/
    name: b1.png
